const usersDb = [
  {
    id: 1,
    name: "Yell Htut",
    username: "yellhtut",
    email: "yellhtut4@gmail.com",
    password: "admin123",
    role: "admin", // e.g., CEO, Sales Manager
    redirect_route: "dashboard",
    path: ["dashboard", "members"],
    refreshToken: "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiYjQxMzQ3YmQ1NGJhNDYyMjYxMDMxMDU1OWE1MWFhZDMxYmQ2MDliMjc3OGVmOTA4ZDdkOWUzMDRlNmI5MzljODU3ZTc5MzczNGQwZDhkMTQiLCJpYXQiOjE3MzUxMTQyNzYuMDY5NzQxLCJuYmYiOjE3MzUxMTQyNzYuMDY5NzQ0LCJleHAiOjE3NTA4MzkwNzUuNzQzNzIzLCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.gFdWRfa-8NouEenEIvPK1QAW5z2tE31AeYdraPG03BTakffKL8F7Q_DfVUwKiSOxAB_hN2eSLJiXeROg2F8WiMvyKVz_sgeYBeR8ZIaB0GAsdagjCGoXU5Mj-7shQ1zZjdIMlVJ39_O5xZPivHnXG1fjVfxbU8V9ih4sWn1FjWE7F1hZZPlc89fDsbIgNpOaGnPBWqtLi8ekaWxDUwesZ-NL1yexWZeTgN_Rc3DfrIjxRJXkbvo_h79b-bUxPtYBcclFIl0WM70d0RhB8bQamNZkXbPWQdDmrE21GyxUK2gq1igmDP-mdhPkHeGpwxm1Q76kpOrmQgl2pLzy6HDXyxEpWoqHdl_42NoyOXEn9x-4qMyQf5c6eCHtzky-OGiAVM371K3qejeNhR00F77wXXfPPcm4loS7S8Y3zW2s4YoS6yCQ8WodQDfuE_Guc",
    permission: {
      dashboard: {
        list: true,
        add: true,
        create: true,
        edit: true,
        update: true,
        hide_show: false,
        details: true,
        history: true,
        delete: true,
      },
      members: {
        list: true,
        add: true,
        create: true,
        edit: true,
        update: true,
        hide_show: false,
        details: true,
        history: true,
        delete: true,
      },
    },
  },
];

const navDb = [
  {
    id: 1,
    name: "Sell",
    route: "sale",
    iconPath: "sell.svg",
    iconActivePath: "sell_white.svg",
    children: [],
  },
  {
    id: 2,
    name: "Inventory",
    route: "inventory",
    iconPath: "inventory.svg",
    iconActivePath: "inventory_white.svg",
    children: [],
  },
  {
    id: 3,
    name: "Dashboard",
    route: "dashboard",
    iconPath: "dashboard.svg",
    iconActivePath: "dashboard_white.svg",
    children: [],
  },

];

const sampleUsers = [
  {
    id: 1,
    name: "Tony Reichert",
    role: "CEO",
    team: "Management",
    status: "active",
    age: "29",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/male/1.png",
    email: "tony.reichert@example.com",
  },
  {
    id: 2,
    name: "Zoey Lang",
    role: "Tech Lead",
    team: "Development",
    status: "paused",
    age: "25",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/female/1.png",
    email: "zoey.lang@example.com",
  },
  {
    id: 3,
    name: "Jane Fisher",
    role: "Sr. Dev",
    team: "Development",
    status: "active",
    age: "22",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/female/2.png",
    email: "jane.fisher@example.com",
  },
  {
    id: 4,
    name: "William Howard",
    role: "C.M.",
    team: "Marketing",
    status: "vacation",
    age: "28",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/male/2.png",
    email: "william.howard@example.com",
  },
  {
    id: 5,
    name: "Kristen Copper",
    role: "S. Manager",
    team: "Sales",
    status: "active",
    age: "24",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/female/3.png",
    email: "kristen.cooper@example.com",
  },
  {
    id: 6,
    name: "Brian Kim",
    role: "P. Manager",
    team: "Management",
    age: "29",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/male/3.png",
    email: "brian.kim@example.com",
    status: "active",
  },
  {
    id: 7,
    name: "Michael Hunt",
    role: "Designer",
    team: "Design",
    status: "paused",
    age: "27",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/male/4.png",
    email: "michael.hunt@example.com",
  },
  {
    id: 8,
    name: "Samantha Brooks",
    role: "HR Manager",
    team: "HR",
    status: "active",
    age: "31",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/female/4.png",
    email: "samantha.brooks@example.com",
  },
  {
    id: 9,
    name: "Frank Harrison",
    role: "F. Manager",
    team: "Finance",
    status: "vacation",
    age: "33",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/male/5.png",
    email: "frank.harrison@example.com",
  },
  {
    id: 10,
    name: "Emma Adams",
    role: "Ops Manager",
    team: "Operations",
    status: "active",
    age: "35",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/female/5.png",
    email: "emma.adams@example.com",
  },
  {
    id: 11,
    name: "Brandon Stevens",
    role: "Jr. Dev",
    team: "Development",
    status: "active",
    age: "22",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/male/7.png",
    email: "brandon.stevens@example.com",
  },
  {
    id: 12,
    name: "Megan Richards",
    role: "P. Manager",
    team: "Product",
    status: "paused",
    age: "28",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/female/7.png",
    email: "megan.richards@example.com",
  },
  {
    id: 13,
    name: "Oliver Scott",
    role: "S. Manager",
    team: "Security",
    status: "active",
    age: "37",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/male/8.png",
    email: "oliver.scott@example.com",
  },
  {
    id: 14,
    name: "Grace Allen",
    role: "M. Specialist",
    team: "Marketing",
    status: "active",
    age: "30",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/female/8.png",
    email: "grace.allen@example.com",
  },
  {
    id: 15,
    name: "Noah Carter",
    role: "IT Specialist",
    team: "I. Technology",
    status: "paused",
    age: "31",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/male/9.png",
    email: "noah.carter@example.com",
  },
  {
    id: 16,
    name: "Ava Perez",
    role: "Manager",
    team: "Sales",
    status: "active",
    age: "29",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/female/9.png",
    email: "ava.perez@example.com",
  },
  {
    id: 17,
    name: "Liam Johnson",
    role: "Data Analyst",
    team: "Analysis",
    status: "active",
    age: "28",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/male/11.png",
    email: "liam.johnson@example.com",
  },
  {
    id: 18,
    name: "Sophia Taylor",
    role: "QA Analyst",
    team: "Testing",
    status: "active",
    age: "27",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/female/11.png",
    email: "sophia.taylor@example.com",
  },
  {
    id: 19,
    name: "Lucas Harris",
    role: "Administrator",
    team: "Information Technology",
    status: "paused",
    age: "32",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/male/12.png",
    email: "lucas.harris@example.com",
  },
  {
    id: 20,
    name: "Mia Robinson",
    role: "Coordinator",
    team: "Operations",
    status: "active",
    age: "26",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/female/12.png",
    email: "mia.robinson@example.com",
  },
];

module.exports = {
  usersDb,
  navDb,
  sampleUsers
};
