import localFont from "next/font/local";
import "./styles/globals.css";
import {Providers} from "./providers";
import Header from "@/app/components/Header/Header"; // for nextui

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='dark'>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} >
        <Providers>
          <Header/>
          {children}
        </Providers>
      </body>
    </html>
  );
}
