// src/app/metadata.js
import process from "next/dist/build/webpack/loaders/resolve-url-loader/lib/postcss";

export const metadata = {
  metadataBase: new URL('http://196.1.1.154:4000'),
  title: "NextJS App",
  description: "Generated by create next app",
  openGraph: {
    title: "NextJS App",
    description: "Generated by create next app",
    images: [
      {
        url: "../../public/next.svg",
        width: 180,
        height: 38,
        alt: "A description of the image for accessibility",
      },
    ],
  },
}


